<?php

namespace Database\Seeders;

use App\Models\TrainingClass;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class OldTrainingClassSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $oldData = [
            [
                'user_id' => 1,
                'instructor' => 'William',
                'location' => 'Liikuntamylly',
                'class_date' => '2024-07-06',
                'class_description' => 'Nogi',
                'class_duration' => (int)'60',
                'rounds' => (int)'4',
                'round_duration' => (int)'5',
            ],
            [
                'user_id' => 1,
                'instructor' => 'William',
                'location' => 'Liikuntamylly',
                'class_date' => '2024-07-06',
                'class_description' => 'Nogi',
                'class_duration' => (int)'60',
                'rounds' => (int)'4',
                'round_duration' => (int)'5',
            ],
            [
                'user_id' => 1,
                'instructor' => 'Open mat',
                'location' => 'Fx jiujitsu',
                'class_date' => '2024-08-16',
                'class_description' => 'Open mat',
                'class_duration' => (int)'90',
                'rounds' => (int)'6',
                'round_duration' => (int)'8',
            ],
            [
                'user_id' => 1,
                'instructor' => 'Open mat',
                'location' => 'Fx jiujitsu',
                'class_date' => '2024-08-17',
                'class_description' => 'Open mat',
                'class_duration' => (int)'45',
                'rounds' => (int)'5',
                'round_duration' => (int)'5',
            ],
            [
                'user_id' => 1,
                'instructor' => 'Open mat',
                'location' => 'Fx jiujitsu',
                'class_date' => '2024-08-18',
                'class_description' => 'Open mat',
                'class_duration' => (int)'75',
                'rounds' => (int)'6',
                'round_duration' => (int)'5',
            ],
            [
                'user_id' => 1,
                'instructor' => 'Open mat',
                'location' => 'Fx Jiujitsu',
                'class_date' => '2024-08-25',
                'class_description' => 'Open mat',
                'class_duration' => (int)'90',
                'rounds' => (int)'7',
                'round_duration' => (int)'5',
            ],
            [
                'user_id' => 1,
                'instructor' => 'Open mat',
                'location' => 'Jyvaskyla Fight Club',
                'class_date' => '2024-08-24',
                'class_description' => 'Open mat',
                'class_duration' => (int)'60',
                'rounds' => (int)'7',
                'round_duration' => (int)'5',
            ],
            [
                'user_id' => 1,
                'instructor' => 'Open mat',
                'location' => 'Jyväskylä Fight Club',
                'class_date' => '2024-09-14',
                'class_description' => 'Open mat',
                'class_duration' => (int)'50',
                'rounds' => (int)'8',
                'round_duration' => (int)'4',
            ],
            [
                'user_id' => 1,
                'instructor' => 'Open mat',
                'location' => 'Jyväskylä fight club',
                'class_date' => '2024-09-28',
                'class_description' => 'Open mat',
                'class_duration' => (int)'50',
                'rounds' => (int)'9',
                'round_duration' => (int)'4',
            ],
            [
                'user_id' => 1,
                'instructor' => '?',
                'location' => 'Jyväskylä Fight Club',
                'class_date' => '2024-10-10',
                'class_description' => 'Pystypaini',
                'class_duration' => (int)'60',
                'rounds' => (int)'0',
                'round_duration' => (int)'0',
            ],
            [
                'user_id' => 1,
                'instructor' => '?',
                'location' => 'Jyväskylä Fight Club',
                'class_date' => '2024-10-10',
                'class_description' => 'Pystypaini',
                'class_duration' => (int)'60',
                'rounds' => (int)'0',
                'round_duration' => (int)'0',
            ],
            [
                'user_id' => 1,
                'instructor' => '-',
                'location' => 'Jyväskylä Fight Club',
                'class_date' => '2024-10-12',
                'class_description' => 'Open mat',
                'class_duration' => (int)'45',
                'rounds' => (int)'7',
                'round_duration' => (int)'4',
            ],
            [
                'user_id' => 1,
                'instructor' => '-',
                'location' => 'Jyväskylä Fight Club',
                'class_date' => '2024-10-19',
                'class_description' => 'Open mat',
                'class_duration' => (int)'60',
                'rounds' => (int)'7',
                'round_duration' => (int)'4',
            ],
            [
                'user_id' => 1,
                'instructor' => '-',
                'location' => 'Jyväskylä Fight Club',
                'class_date' => '2024-10-26',
                'class_description' => 'Open mat',
                'class_duration' => (int)'60',
                'rounds' => (int)'7',
                'round_duration' => (int)'4',
            ],
            [
                'user_id' => 1,
                'instructor' => '-',
                'location' => 'Jyväskylä Fight Club',
                'class_date' => '2024-11-02',
                'class_description' => 'Open mat',
                'class_duration' => (int)'60',
                'rounds' => (int)'7',
                'round_duration' => (int)'5',
            ],
            [
                'user_id' => 1,
                'instructor' => '-',
                'location' => 'FX',
                'class_date' => '2024-12-07',
                'class_description' => 'Open mat',
                'class_duration' => (int)'60',
                'rounds' => (int)'6',
                'round_duration' => (int)'6',
            ],
            [
                'user_id' => 1,
                'instructor' => '-',
                'location' => 'FX Jiujitsu',
                'class_date' => '2024-12-27',
                'class_description' => 'Open mat',
                'class_duration' => (int)'60',
                'rounds' => (int)'10',
                'round_duration' => (int)'6',
            ],
            [
                'user_id' => 1,
                'instructor' => '-',
                'location' => 'FX Jiujitsu',
                'class_date' => '2024-12-28',
                'class_description' => 'Open mat',
                'class_duration' => (int)'60',
                'rounds' => (int)'7',
                'round_duration' => (int)'5',
            ],
            [
                'user_id' => 1,
                'instructor' => '-',
                'location' => 'FX Jiujitsu',
                'class_date' => '2025-01-02',
                'class_description' => 'Open mat',
                'class_duration' => (int)'60',
                'rounds' => (int)'7',
                'round_duration' => (int)'6',
            ],
            [
                'user_id' => 1,
                'instructor' => '-',
                'location' => 'FX Jiujitsu',
                'class_date' => '2025-01-05',
                'class_description' => 'Open mat',
                'class_duration' => (int)'75',
                'rounds' => (int)'9',
                'round_duration' => (int)'6',
            ],
            [
                'user_id' => 1,
                'instructor' => '-',
                'location' => 'FX Jiujitsu',
                'class_date' => '2025-01-10',
                'class_description' => 'Open mat',
                'class_duration' => (int)'60',
                'rounds' => (int)'8',
                'round_duration' => (int)'6',
            ],
            [
                'user_id' => 1,
                'instructor' => '-',
                'location' => 'Fx Jiujitsu',
                'class_date' => '2025-01-12',
                'class_description' => 'Open mat',
                'class_duration' => (int)'90',
                'rounds' => (int)'10',
                'round_duration' => (int)'6',
            ],
            [
                'user_id' => 1,
                'instructor' => 'Natsku',
                'location' => 'FX Jiujitsu',
                'class_date' => '2025-01-16',
                'class_description' => 'Nogi',
                'class_duration' => (int)'90',
                'rounds' => (int)'0',
                'round_duration' => (int)'0',
            ],
            [
                'user_id' => 1,
                'instructor' => '-',
                'location' => 'FX Jiujitsu',
                'class_date' => '2025-01-17',
                'class_description' => 'Positiopaini',
                'class_duration' => (int)'60',
                'rounds' => (int)'10',
                'round_duration' => (int)'6',
            ],
            [
                'user_id' => 1,
                'instructor' => '-',
                'location' => 'FX Jiujitsu',
                'class_date' => '2025-01-18',
                'class_description' => 'Open mat',
                'class_duration' => (int)'60',
                'rounds' => (int)'9',
                'round_duration' => (int)'6',
            ],
            [
                'user_id' => 1,
                'instructor' => 'Roni',
                'location' => 'FX Jiujitsu',
                'class_date' => '2025-01-21',
                'class_description' => 'Passing from outside.\r\n\r\nDrive with knee in, kinda like leg drag. Keep grip of both ankles and move the legs to either side and drive through your knee, kinda like leg drag. Goal is to put pressure so that opponent lifts his hips, then you can easily turn',
                'class_duration' => (int)'90',
                'rounds' => (int)'6',
                'round_duration' => (int)'6',
            ],
            [
                'user_id' => 1,
                'instructor' => '-',
                'location' => 'FX Jiujitsu',
                'class_date' => '2025-02-06',
                'class_description' => 'NoGi ',
                'class_duration' => (int)'90',
                'rounds' => (int)'4',
                'round_duration' => (int)'6',
            ],
            [
                'user_id' => 1,
                'instructor' => '-',
                'location' => 'FX Jiujitsu',
                'class_date' => '2025-02-07',
                'class_description' => 'Open mat',
                'class_duration' => (int)'90',
                'rounds' => (int)'11',
                'round_duration' => (int)'6',
            ],
            [
                'user_id' => 1,
                'instructor' => '-',
                'location' => 'Fx Jiujitsu',
                'class_date' => '2025-02-08',
                'class_description' => 'Open mat',
                'class_duration' => (int)'70',
                'rounds' => (int)'12',
                'round_duration' => (int)'5',
            ],
            [
                'user_id' => 1,
                'instructor' => '-',
                'location' => 'Fx jiujitsu',
                'class_date' => '2025-02-09',
                'class_description' => 'Open mat',
                'class_duration' => (int)'80',
                'rounds' => (int)'12',
                'round_duration' => (int)'5',
            ],
            [
                'user_id' => 1,
                'instructor' => '-',
                'location' => 'Fx jiujitsu',
                'class_date' => '2025-02-14',
                'class_description' => 'Open mat',
                'class_duration' => (int)'80',
                'rounds' => (int)'10',
                'round_duration' => (int)'6',
            ],
            [
                'user_id' => 1,
                'instructor' => '-',
                'location' => 'Fx Jiujitsu',
                'class_date' => '2025-02-16',
                'class_description' => 'Kisatreeni',
                'class_duration' => (int)'75',
                'rounds' => (int)'12',
                'round_duration' => (int)'5',
            ],
            [
                'user_id' => 1,
                'instructor' => 'Roni',
                'location' => 'Fx Jiujitsu',
                'class_date' => '2025-02-18',
                'class_description' => 'K guard entry, käsilukko ja triangeli k-guardista',
                'class_duration' => (int)'90',
                'rounds' => (int)'4',
                'round_duration' => (int)'7',
            ],
            [
                'user_id' => 1,
                'instructor' => 'Natsku',
                'location' => 'Fx Jiujitsu',
                'class_date' => '2025-02-20',
                'class_description' => 'K guard',
                'class_duration' => (int)'90',
                'rounds' => (int)'4',
                'round_duration' => (int)'5',
            ],
            [
                'user_id' => 1,
                'instructor' => '-',
                'location' => 'Fx Jiujitsu',
                'class_date' => '2025-02-21',
                'class_description' => 'Open mat',
                'class_duration' => (int)'90',
                'rounds' => (int)'9',
                'round_duration' => (int)'6',
            ],
            [
                'user_id' => 1,
                'instructor' => '-',
                'location' => 'Fx Jiujitsu',
                'class_date' => '2025-02-23',
                'class_description' => 'Open mat',
                'class_duration' => (int)'75',
                'rounds' => (int)'9',
                'round_duration' => (int)'6',
            ],
            [
                'user_id' => 1,
                'instructor' => 'Roni',
                'location' => 'FX Jiujitsu',
                'class_date' => '2025-02-25',
                'class_description' => 'Nogi, single x guard, saddle entry',
                'class_duration' => (int)'90',
                'rounds' => (int)'4',
                'round_duration' => (int)'6',
            ],
            [
                'user_id' => 1,
                'instructor' => 'Natsku',
                'location' => 'FX Jiujitsu',
                'class_date' => '2025-02-27',
                'class_description' => 'Nogi, bear trap sweeps etc',
                'class_duration' => (int)'90',
                'rounds' => (int)'6',
                'round_duration' => (int)'3',
            ],
            [
                'user_id' => 1,
                'instructor' => '-',
                'location' => 'Fx Jiujitsu',
                'class_date' => '2025-02-28',
                'class_description' => 'Open mat',
                'class_duration' => (int)'75',
                'rounds' => (int)'6',
                'round_duration' => (int)'6',
            ],
            [
                'user_id' => 1,
                'instructor' => '-',
                'location' => 'Fx Jiujitsu',
                'class_date' => '2025-03-02',
                'class_description' => 'Open mat',
                'class_duration' => (int)'75',
                'rounds' => (int)'7',
                'round_duration' => (int)'6',
            ],
            [
                'user_id' => 1,
                'instructor' => 'Roni',
                'location' => 'Fx Jiujitsu',
                'class_date' => '2025-03-04',
                'class_description' => 'Sidesta escapee niin että katkaa yhellä jalalla, toinen kaverin lantiossa kiinni ja hakee aukkoa. Jos kaveri kääntyy päin niin oma kyynärpää mattoon ja kaverin kauempaan lantioon ja ujuta jalka mattoa pitkin',
                'class_duration' => (int)'90',
                'rounds' => (int)'5',
                'round_duration' => (int)'6',
            ],
            [
                'user_id' => 1,
                'instructor' => 'Niko',
                'location' => 'Fx Jiujitsu',
                'class_date' => '2025-03-11',
                'class_description' => 'Side backtake',
                'class_duration' => (int)'90',
                'rounds' => (int)'5',
                'round_duration' => (int)'7',
            ],
            [
                'user_id' => 1,
                'instructor' => '-',
                'location' => 'Fx Jiujitsu',
                'class_date' => '2025-03-07',
                'class_description' => 'Open mat',
                'class_duration' => (int)'70',
                'rounds' => (int)'9',
                'round_duration' => (int)'6',
            ],
            [
                'user_id' => 1,
                'instructor' => '-',
                'location' => 'Fx Jiujitsu',
                'class_date' => '2025-03-09',
                'class_description' => 'Open mat',
                'class_duration' => (int)'90',
                'rounds' => (int)'9',
                'round_duration' => (int)'6',
            ],
            [
                'user_id' => 1,
                'instructor' => 'Natsku',
                'location' => 'FX Jiujitsu',
                'class_date' => '2025-03-13',
                'class_description' => 'nogi',
                'class_duration' => (int)'90',
                'rounds' => (int)'4',
                'round_duration' => (int)'6',
            ],
            [
                'user_id' => 1,
                'instructor' => '-',
                'location' => 'FX Jiujitsu',
                'class_date' => '2025-03-16',
                'class_description' => 'Open mat',
                'class_duration' => (int)'90',
                'rounds' => (int)'6',
                'round_duration' => (int)'6',
            ],
            [
                'user_id' => 1,
                'instructor' => '-',
                'location' => 'Liikuntamylly',
                'class_date' => '2025-03-23',
                'class_description' => 'Nogi reenailua Rikun kans',
                'class_duration' => (int)'60',
                'rounds' => (int)'5',
                'round_duration' => (int)'4',
            ],
            [
                'user_id' => 1,
                'instructor' => '-',
                'location' => 'FX Jiujitsu',
                'class_date' => '2025-03-21',
                'class_description' => 'Open mat',
                'class_duration' => (int)'60',
                'rounds' => (int)'6',
                'round_duration' => (int)'6',
            ],
            [
                'user_id' => 1,
                'instructor' => 'Aku',
                'location' => 'Fx Jiujitsu',
                'class_date' => '2025-03-25',
                'class_description' => 'Sidestä selkään ja mounttiin, polvi hajos sparrissa',
                'class_duration' => (int)'90',
                'rounds' => (int)'6',
                'round_duration' => (int)'5',
            ],
        ];

        foreach ($oldData as $data) {
            TrainingClass::create([
                'user_id' => $data['user_id'],
                'instructor' => $data['instructor'],
                'location' => $data['location'],
                'class_date' => $data['class_date'],
                'class_description' => $data['class_description'],
                'class_duration' => (int)$data['class_duration'],
                'rounds' => (int)$data['rounds'],
                'round_duration' => (int)$data['round_duration'],
            ]);
        }
    }
}
