name: Deploy to production

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'
        extensions: bcmath, ctype, dom, fileinfo, json, mbstring, mysqli, openssl, pdo_mysql, tokenizer, xml
        coverage: none

    - name: Install Node dependencies
      run: npm ci

    - name: Install Composer dependencies
      run: composer install --no-dev --optimize-autoloader

    - name: Build React app
      run: npm run build

    - name: Deploy to server
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

        # Copy Laravel application files
        scp -o StrictHostKeyChecking=no -r app/ ${{ secrets.USER }}@${{ secrets.HOST }}:/var/www/william/
        scp -o StrictHostKeyChecking=no -r config/ ${{ secrets.USER }}@${{ secrets.HOST }}:/var/www/william/
        scp -o StrictHostKeyChecking=no -r routes/ ${{ secrets.USER }}@${{ secrets.HOST }}:/var/www/william/
        scp -o StrictHostKeyChecking=no -r database/ ${{ secrets.USER }}@${{ secrets.HOST }}:/var/www/william/
        scp -o StrictHostKeyChecking=no -r resources/ ${{ secrets.USER }}@${{ secrets.HOST }}:/var/www/william/
        scp -o StrictHostKeyChecking=no -r bootstrap/ ${{ secrets.USER }}@${{ secrets.HOST }}:/var/www/william/
        scp -o StrictHostKeyChecking=no -r public/ ${{ secrets.USER }}@${{ secrets.HOST }}:/var/www/william/
        scp -o StrictHostKeyChecking=no artisan ${{ secrets.USER }}@${{ secrets.HOST }}:/var/www/william/
        scp -o StrictHostKeyChecking=no composer.json ${{ secrets.USER }}@${{ secrets.HOST }}:/var/www/william/
        scp -o StrictHostKeyChecking=no composer.lock ${{ secrets.USER }}@${{ secrets.HOST }}:/var/www/william/

    - name: Run server commands
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.HOST }} << 'EOF'
          cd /var/www/grapplingtracker/
          composer install --no-dev --optimize-autoloader
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          php artisan migrate --force
        EOF
